Channels:
    - conda-forge
dependencies:
    - python=3.7.*
    - numpy
    - pandas
    - xarray
    - matplotlib
    - cartopy
    - fsspec
    - scipy
    - scikit-learn
    - aiohttp
    - requests
   